/**
 * Defect Microservice
 * This is the API spec for retrieving all defects. These defects will be stored locally on the VSAs mobile device. Authorization details will be updated once we have confirmed the security scheme we are using.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mdclarke@deloitte.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Item } from './item';
import { ImNumberAdditionalInfo } from './imNumberAdditionalInfo';


export interface ImNumber { 
    imNumber?: number;
    imDescription?: string;
    forVehicleType?: Array<ImNumber.ForVehicleTypeEnum>;
    additionalInfo?: ImNumberAdditionalInfo;
    items?: Array<Item>;
}
export namespace ImNumber {
    export type ForVehicleTypeEnum = 'psv' | 'hgv' | 'trl';
    export const ForVehicleTypeEnum = {
        Psv: 'psv' as ForVehicleTypeEnum,
        Hgv: 'hgv' as ForVehicleTypeEnum,
        Trl: 'trl' as ForVehicleTypeEnum
    };
}


