/**
 * Defect Microservice
 * This is the API spec for retrieving all defects. These defects will be stored locally on the VSAs mobile device. Authorization details will be updated once we have confirmed the security scheme we are using.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mdclarke@deloitte.co.uk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PsvAdditionalInfoLocation { 
    vertical?: Array<PsvAdditionalInfoLocation.VerticalEnum> | null;
    horizontal?: Array<PsvAdditionalInfoLocation.HorizontalEnum> | null;
    lateral?: Array<PsvAdditionalInfoLocation.LateralEnum> | null;
    longitudinal?: Array<PsvAdditionalInfoLocation.LongitudinalEnum> | null;
    rowNumber?: Array<number> | null;
    seatNumber?: Array<number> | null;
    axleNumber?: Array<number> | null;
}
export namespace PsvAdditionalInfoLocation {
    export type VerticalEnum = 'upper' | 'lower';
    export const VerticalEnum = {
        Upper: 'upper' as VerticalEnum,
        Lower: 'lower' as VerticalEnum
    };
    export type HorizontalEnum = 'inner' | 'outer';
    export const HorizontalEnum = {
        Inner: 'inner' as HorizontalEnum,
        Outer: 'outer' as HorizontalEnum
    };
    export type LateralEnum = 'nearside' | 'centre' | 'offside';
    export const LateralEnum = {
        Nearside: 'nearside' as LateralEnum,
        Centre: 'centre' as LateralEnum,
        Offside: 'offside' as LateralEnum
    };
    export type LongitudinalEnum = 'front' | 'rear';
    export const LongitudinalEnum = {
        Front: 'front' as LongitudinalEnum,
        Rear: 'rear' as LongitudinalEnum
    };
}


